define([], function() {
    return {
      address: "Adresse",
      cases: "Sager",
      city: "By",
      customer: "Kunde",
      customers: "Kunder",
      favorites: "Favoritter",
      mycases: "Mine sager",
      mycustomers: "Mine kunder",
      mypage: "Min side",
      name: "Navn",
      new: "Ny",
      number: "Nummer",
      o90number: "Ø90 Nummer",
      postalcode: "Postnummer",
      processing: "Behandler",
      queued: "I kø",
      recents: "Seneste",
      results: "Resultater",
      search: "Søg",
      searchspecific: "Søg på",
      showonlymycases: "Vis kun mine sager",
      site: "Side",
      startdate: "Startdato",
      type: "Type",
      "PropertyPaneDescription": "Beskrivelse",
      "BasicGroupName": "Gruppenavn",
      "DescriptionFieldLabel": "Beskrivelsesfelt",
      "AppLocalEnvironmentSharePoint": "Appen kører på din lokale SharePoint-environment som en webdel",
      "AppLocalEnvironmentTeams": "Appen kører på din lokale Microsoft Teams-environment",
      "AppLocalEnvironmentOffice": "Appen kører på din lokale environment i office.com",
      "AppLocalEnvironmentOutlook": "Appen kører på din lokale environment i Outlook",
      "AppSharePointEnvironment": "Appen kører på SharePoint-side",
      "AppTeamsTabEnvironment": "Appen kører i Microsoft Teams",
      "AppOfficeEnvironment": "Appen kører i office.com",
      "AppOutlookEnvironment": "Appen kører i Outlook",
      "UnknownEnvironment": "Appen kører i en ukendt environment"
    }
  });