define([], function() {
  return {
    address: "Address",
    cases: "Cases",
    city: "City",
    customer: "Customer",
    customers: "Customers",
    favorites: "Favorites",
    mycases: "My cases",
    mycustomers: "My customers",
    mypage: "My Page",
    name: "Name",
    new: "New",
    number: "Number",
    o90number: "Ø90 Number",
    postalcode: "Postal Code",
    processing: "Processing",
    queued: "Queued",
    recents: "Recents",
    results: "Results",
    search: "Search",
    searchspecific: "Search by",
    showonlymycases: "Show only my cases",
    site: "Site",
    startdate: "Start Date",
    type: "Type",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment"
  }
});