define([], function() {
  return {
    advanced: "Avanceret",
    create: "Opret",
    createAndOpen: "Opret og åbn",
    createSelected: "Opret valgte",
    creationDetailsTitle: "Oprettelsesdetaljer",
    deselectAll: "Fravælg alle",
    esdhTitle: "Elektronisk sag- og dokumenthåndtering",
    file: "Fil",
    filename: "Filnavn",
    loadingText: "Indlæser...",
    modified: "Ændret",
    newFilename: "Nyt filnavn",
    preview: "Forhåndsvisning",
    previewFile: "Forhåndsvis fil",
    saveLocation: "Placering",
    search: "Søg",
    searchCategory: "Søg kategori",
    selectAll: "Vælg alle",
    selectedCategoryTemplatesTitle: "Valgte kategori skabeloner",
    selectedCategory: "Valgte kategori",
    selectedTemplatesTotal: "Valgte skabeloner i alt",
    settings: "Indstillinger",
    simple: "Enkel",
    templateCategoriesTitle: "Skabelonkategorier",
    version: "Version",
    "Command1": "Kommando 1",
    "Command2": "Kommando 2"
  }
});